# Docker Compose version
version: "3.8"

services:
  nexus:
    build: ./nexus
    ports:
    - "8081:8081"
    volumes:
    # if container served any other purposes, it wouldn't be great to mount entire /opt folder as a volume
      -  nexus-config:/opt

  runner:
    build:
      context: ./runner
    env_file: 
      - .env
    links:
      - "nexus"

volumes:
  nexus-config: